CREATE TABLE "DEMO"."CLOBDEMO" 
   (	"ID" NUMBER(*,0), 
	"CLOBCOL" CLOB, 
	 CONSTRAINT "CLOBDEMO_PK" PRIMARY KEY ("ID")
  );
  
  
CREATE OR REPLACE PROCEDURE DEMO.PUTSTREAM(idx INTEGER,STREAMIN CLOB) AS
BEGIN
INSERT INTO CLOBDEMO c (c.ID,c.CLOBCOL) VALUES(idx,STREAMIN);
END;

  
  
  
